# Config file for automatic testing at travis-ci.com
--- 
after_success: 
  - codecov
before_install: 
  - "python --version"
  - "pip install -U pip"
  - "pip install -U pytest"
  - "pip install codecov"
install: 
  - "pip install \".[test]\" ."
language: python
python: 
  - 3.7
  - 3.8
script: pytest

