# Config file for automatic testing at travis-ci.com
version: ~> 1.0
env:
  - TOX_ENV=py38
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - CC_TEST_REPORTER_ID=d8b6d79f2be4dddc63b5feb3e4a607e7da5079babd5b52dd6c29c519845a6577
    - CCTR=./cc-test-reporter
language: python
python:
  - 3.8
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis
# Command to run tests, e.g. python setup.py test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build
build:
  nodes:
    coverage:
      tests:
        override:
          - command: './run-tests.sh'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
script: tox -e $TOX_ENV
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
  - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: 0LL13
  #  password:
  #    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: 0LL13/person
    python: 3.8
after_script:
  - $CCTR upload-coverage -r .coverage
  - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT
  - rm -f config/application.yml
after_success:
  - codecov -e TOX_ENV

