# Config file for automatic testing at travis-ci.com
--- 
after_script: 
  - "$CCTR upload-coverage -r .coverage"
  - "$CCTR after-build --exit-code $TRAVIS_TEST_RESULT"
  - "rm -f config/application.yml"
after_success: 
  - codecov -e TOX_ENV
  - coveralls
before_install: 
  - "python --version"
  - "pip install -U pip"
  - "pip install -U pytest"
  - "pip install codecov"
  - "sudo apt-get install jq"
before_script: 

build: 
  nodes: 
    coverage: 
      tests: 
        override: 
          - 
            command: ./run-tests.sh
            coverage: 
              config_file: .coveragerc
              file: .coverage
              format: py-cc
deploy: 
  distributions: "sdist bdist_wheel"
  provider: GitHub
  true: 
    python: 3.8
    repo: 0LL13/person
    tags: true
  user: 0LL13
env: 
  - TOX_ENV=py38
install: 
  - "pip install -U tox-travis \".[test]\" ."
language: python
python: 
  - 3.8
script: coverage run --source personroles -m pytest
