---
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - 
        uses: actions/checkout@master
      - 
        name: "Run codacy-coverage-reporter"
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          coverage-reports: .coverage
          project-token: $CODACY_PROJECT_TOKEN
name: codacy-coverage-reporter
true:
  - push
